---
id: Cache
name: Cache
full: Caching library
description: >-
  A simple, functional caching library, with the option to store the cached data
  on the filesystem, APCu, eAcclerator, XCache, Memcache, MongoDB, Redis, user
  session, an SQL table, or a combination of these.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Cache
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha5
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/compress_fast: ^2
      horde/exception: ^3
      horde/util: ^3
    ext:
      hash: '*'
  optional:
    composer:
      horde/db: ^3
      horde/hashtable: ^2
      horde/log: ^3
      horde/memcache: ^3
      horde/mongo: ^2
    ext:
      eaccelerator: 0.9.5
      xcache: '*'
      apcu: '*'
  dev:
    composer:
      horde/test: ^3
      horde/db: ^3
      horde/hashtable: ^2
      horde/log: ^3
      horde/memcache: ^3
      horde/mongo: ^2
